apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: commit-carrier-allchannel-supplychain6-1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: commit-carrier-allchannel-supplychain6-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-chaincode-commit
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 2.2.2
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://host.docker.internal:8200
      authpath: localcarrier
      adminsecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/orderer
      secretpath: secretsv2
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 6
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies: ''
      initrequired: False
      repository:
        hostname: "github.com"
        git_username: "Anjalikarhana"
        url: github.com/Anjalikarhana/bevel-samples.git
        branch: main
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode/
      pdc:
        enabled: false
        collectionsconfig:  ""
    channel:
      name: allchannel
    endorsers:
      creator: carrier-net
      name:  carrier  manufacturer 
      corepeeraddress:  peer0.carrier-net:7051  peer0.manufacturer-net:7051 
      nameslist: 
        - name: carrier
        - name: manufacturer
