apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-orderernode
  values:
    metadata:
      namespace: supplychain-net
      network:
        version: 2.2.2
      images:
        orderer: ghcr.io/hyperledger/bevel-fabric-orderer:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
      ordererAddress: orderer1.supplychain-net:7050

    consensus:
      name: raft

    storage:
      storageclassname: supplychain-bevel-storageclass
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050
        metrics: 
          enabled: False
          clusteripport: 9443

    vault:
      address: http://host.docker.internal:8200
      role: vault-role
      authpath: localsupplychain
      type: hashicorp
      secretprefix: secretsv2/data/supplychain/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: ""
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com
    genesis: |-
      CiIaIFjjVOMWOVsTEQ/bsHPjR+uKqzz4KpKp/orZoLrZ5dVMEtJeCs9eCsxeCngKWggBEAEaBgjy
      +tiwBiIKc3lzY2hhbm5lbCpAYjc1YzAxMzc2ZjljY2FhNWU0MWMzZGI4ZjMzNzA4ZjA0ZmQ3ZTIx
      ZWVlODY1M2Y2ZTBmOWU2MDcyNTUwZDYyNRIaEhj4lea13f1mKWg+KgERwJY3pGo/F2hxa/cSz10K
      zF0SyV0SySsKB09yZGVyZXISvSsSghcKDnN1cHBseWNoYWluTVNQEu8WGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVR1F2dDZjVVY4WDY4VjhwaXBOUDl1UFMwc3pRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NalF3TkRFd01EWTFOVFEzV2hjTk1qY3dNVEk1TURZMU5UUTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMTVNr
      TXlYRit6N3NlTlc1L3FGSkZ5YUI1YlJadlVLU0oreXduUTJTVUU1cFgxRmpnWUMKRzN2cjJhNmU1
      S0hYQlN6c3QyVFBESEtoUVRMbWxqTEUxUHVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0FnQnJXS2N4MDVudnFBZTlkZVBvZnhF
      clNEekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCTGxnbGdTclVLR2hzbUd4WkpKNndKQ3crcy9M
      Qk5OQjNodWZIc1ZLd0IKOWdJaEFNQkdCaGlQdk5kTGw1bGtETFp1WmIyendZWTZMQ25TK3ZHSFQ4
      eklMbGVMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lUWS8yWXVWaUIxSkdnazc5NHdEanhjQk8rN1RBS0Jn
      Z3Foa2pPUFFRREFqQmUKTVFzd0NRWURWUVFHRXdKSFFqRVBNQTBHQTFVRUNBd0dURzl1Wkc5dU1R
      OHdEUVlEVlFRSERBWk1iMjVrYjI0eApFREFPQmdOVkJBb01CMDl5WkdWeVpYSXhHekFaQmdOVkJB
      TU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREFlCkZ3MHlOREEwTVRBd056QTFNREJhRncweU5U
      QTBNVEF3TnpFd01EQmFNR3d4Q3pBSkJnTlZCQVlUQWtkQ01Sc3cKR1FZRFZRUUhFeEkxTVM0MU1D
      OHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjA5eVpHVnlaWEl4RGpBTQpCZ05WQkFzVEJX
      RmtiV2x1TVI0d0hBWURWUVFEREJWQlpHMXBia0J6ZFhCd2JIbGphR0ZwYmkxdVpYUXdXVEFUCkJn
      Y3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJCVGZsY0RubXB6Ti9aUTZLVTVJUFVsalp0d01y
      alE5enEKRGVNQ1VQNDg0UDE5d09aMC9IWERneGtLbVFJNnlMbXVzYkF6Z2FyMDRWbzNvNkFNYUNH
      NW80SUJGRENDQVJBdwpEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZ
      RFZSME9CQllFRkprVit4VFBrWkNvCmZvbkJRQVdYODR0WG5CRGtNQjhHQTFVZEl3UVlNQmFBRklD
      QUd0WXB6SFRtZStvQjcxMTQraC9FU3RJUE1DUUcKQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRZ
      NU9HUTROelJqT1RZdGQydG5aR1F3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBbHNJOHY3bzZteGZuL0pxSHRiS0pVcVUxTXJGNUlYbVJQWWdpcWFzMWt0Z0NJRGNE
      cDIxaHl2aFIrbkcyCnRXY1pFdzk5YXk1T3BEQmsyVHdQQkRTd0hvSkoKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVR1F2dDZjVVY4WDY4VjhwaXBOUDl1UFMwc3pRd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NalF3TkRFd01EWTFOVFEzV2hjTk1qY3dNVEk1
      TURZMU5UUTNXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJMTVNrTXlYRit6N3NlTlc1L3FGSkZ5YUI1YlJadlVLU0oreXduUTJTVUU1cFgxRmpnWUMK
      RzN2cjJhNmU1S0hYQlN6c3QyVFBESEtoUVRMbWxqTEUxUHVqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0FnQnJXS2N4MDVudnFB
      ZTlkZVBvZnhFclNEekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCTGxnbGdTclVLR2hzbUd4WkpK
      NndKQ3crcy9MQk5OQjNodWZIc1ZLd0IKOWdJaEFNQkdCaGlQdk5kTGw1bGtETFp1WmIyendZWTZM
      Q25TK3ZHSFQ4eklMbGVMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMaNgoJRW5k
      cG9pbnRzEikSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaBkFkbWlucyI4CgZBZG1p
      bnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zKgZB
      ZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NB
      cW1nQXdJQkFnSVViaVJvWVNUZ0NuaXYvcVlRQWgzcDkyQmxFalV3Q2dZSUtvWkl6ajBFQXdJdwpY
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYUXcKSGhjTk1qUXdOREV3TURjd05UQXdXaGNOTWpVd05ERXdNRGN4TURBd1dq
      QnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpH
      OXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3
      WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BR
      SUJCZ2dxaGtqT1BRTUJCd05DQUFSbEwwQnE5RkZPS3JDc0FxRjVHcEIram12cQp4TDNYL1RFSDNF
      aVRxNmtQbS9yWmc0Nm1sOWg2WExMdDFnWTRYR1Rsd0I1YlhtUWM5eWpNTUhaaEtMZUJvNElCCk1E
      Q0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdn
      ckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUbWxpTko0R3V6N0pU
      NUEwaUY3Qzd2R251cwo3akFmQmdOVkhTTUVHREFXZ0JTQWdCcldLY3gwNW52cUFlOWRlUG9meEVy
      U0R6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205
      eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1G
      MGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVs
      RUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05
      eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMd2l4OG5rWk0yUlBEQXcKdkMw
      NG8wS2hCZGVBVWZ2S25zdkc0R1lIR0d6NkFpQm5QR0lxTGFwM21RVk8yN2l4MUZZNm8yOHpJRVc2
      VktQawpNYTNSa2V3YTBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVViaVJvWVNUZ0NuaXYvcVlRQWgz
      cDkyQmxFalV3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qUXdOREV3TURj
      d05UQXdXaGNOTWpVd05ERXdNRGN4TURBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFV
      RUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3
      CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSbEwwQnE5RkZP
      S3JDc0FxRjVHcEIram12cQp4TDNYL1RFSDNFaVRxNmtQbS9yWmc0Nm1sOWg2WExMdDFnWTRYR1Rs
      d0I1YlhtUWM5eWpNTUhaaEtMZUJvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBH
      QTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFB
      TUIwR0ExVWREZ1FXQkJUbWxpTko0R3V6N0pUNUEwaUY3Qzd2R251cwo3akFmQmdOVkhTTUVHREFX
      Z0JTQWdCcldLY3gwNW52cUFlOWRlUG9meEVyU0R6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UK
      WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhh
      VzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURT
      QUF3UlFJaEFMd2l4OG5rWk0yUlBEQXcKdkMwNG8wS2hCZGVBVWZ2S25zdkc0R1lIR0d6NkFpQm5Q
      R0lxTGFwM21RVk8yN2l4MUZZNm8yOHpJRVc2VktQawpNYTNSa2V3YTBRPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIV
      EgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoT
      Q2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8w
      EgAaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJz
      EhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS
      uS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21hbnVm
      YWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVViaTlwVGlFMmpLdDNRd3pO
      TjZVdGw5TmV5UUl3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05W
      QkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUx
      Wm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNO
      TWpRd05ERXdNRFkxT0RVNFdoY05NamN3TVRJNU1EWTFPRFU0V2pCa01Rc3dDUVlEVlFRRwpFd0pE
      U0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZC
      QW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlM
      VzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKNmpLNWhEakNQb3EvTjRV
      VWhCTkpZc3h4eHNXSW5WVjRVcwpHbk9CTXU5WjZaL1g1UU1UY1VoVUJQZktuMU5wM1piT0Q0dnFC
      UlREWXlIU0dTQWFEVnFqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9C
      QVFEQWdHbU1CMEdBMVVkRGdRV0JCU2pqd0JBcWxYSnh4Sm8KREJXM0xtd2xKMlJienpBS0JnZ3Fo
      a2pPUFFRREFnTklBREJGQWlBWmV1aFc5WGRSWHpnZ09OOXpmRkxGWktDbQpUWkFVVU01eEl2R0h0
      cUZpblFJaEFOY213dkdLckFPVk1OL0ZlQVVzbk1iUklXY1ZWdEJjenczdEFxa3p0dlVNCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURF
      RENDQXJlZ0F3SUJBZ0lVSjh2RjhHb0xEWnVjMmZ0OHM4NUNGMUlsdmlNd0NnWUlLb1pJemowRUF3
      SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUy
      TmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qUXdOREV3TURjd09EQXdXaGNOTWpVd05E
      RXdNRGN4TXpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6
      Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJB
      c1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpH
      MXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFR
      Y0RRZ0FFRC94SFEzdnR0blQ0VkpvSVBOZHdXN1E1amVvZnlEL0UvNkRKRURqVDBJM0d4N0tJT3Q2
      RgpGVDMrejhBUjhkaHFBb1FLeHBObVA2bytsNTlpdVppMzNhT0NBU0l3Z2dFZU1BNEdBMVVkRHdF
      Qi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRaS96dE42RXV3aFF6
      aG5rdFVCbmNlM1lTWU1EQWYKQmdOVkhTTUVHREFXZ0JTamp3QkFxbFhKeHhKb0RCVzNMbXdsSjJS
      Ynp6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1pHSTJaamxrWW1JNUxYcGtOelk1TUlH
      WEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEoxWlNJ
      c0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1poWTNS
      MWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21W
      eUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJF
      CkFpQXEvUHpJYjg0eXRsQjFTQlY1WWFkWkQxU1loZXlUdkpIbnJBWjI3UnRXZUFJZ2MyL3FhY21j
      Mm1yV0IxZ3AKekNnZ3psUWM0TTA4VTZSeDF3cW1qNndYN3d3PQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      Q0REQ0NBYktnQXdJQkFnSVViaTlwVGlFMmpLdDNRd3pOTjZVdGw5TmV5UUl3Q2dZSUtvWkl6ajBF
      QXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVF
      Qnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1N
      RTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpRd05ERXdNRFkxT0RVNFdoY05NamN3
      TVRJNU1EWTFPRFU0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05v
      TVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVj
      TUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VH
      Q0NxR1NNNDlBd0VIQTBJQUJKNmpLNWhEakNQb3EvTjRVVWhCTkpZc3h4eHNXSW5WVjRVcwpHbk9C
      TXU5WjZaL1g1UU1UY1VoVUJQZktuMU5wM1piT0Q0dnFCUlREWXlIU0dTQWFEVnFqUWpCQU1BOEdB
      MVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2pq
      d0JBcWxYSnh4Sm8KREJXM0xtd2xKMlJienpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBWmV1aFc5
      WGRSWHpnZ09OOXpmRkxGWktDbQpUWkFVVU01eEl2R0h0cUZpblFJaEFOY213dkdLckFPVk1OL0Zl
      QVVzbk1iUklXY1ZWdEJjenczdEFxa3p0dlVNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEa
      BkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwUEqkU
      CgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3
      SUJBZ0lVY0RaczAzMHY2amNKSkN4Tm9UK0tLOGNjeWprd0NnWUlLb1pJemowRUF3SXcKV2pFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1
      bGREQWVGdzB5Ck5EQTBNVEF3TnpBeU1ETmFGdzB5TnpBeE1qa3dOekF5TUROYU1Gb3hDekFKQmdO
      VkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpF
      UU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUldOR0JCUFhybG0zNmJQdUhjZ3Vh
      WC8xekJCeS9yWllJWERrcnBvQ001NVB2YVluMzJBYXpob09vM0JrdCsKdWN2Rm4rYUlSWWcxUVFP
      cm9xK3hUV3VTbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJ
      QnBqQWRCZ05WSFE0RUZnUVVJc05jdmJmYmo3NmQxWnphQlkrbzUvOXpXV2t3Q2dZSUtvWkl6ajBF
      CkF3SURTQUF3UlFJZ0xDdllVMWJ5ajN1cGdUTEV3aTVjd0hFdnBBNHpwdFNEd0NZNExqTWJVMk1D
      SVFDL3U3VisKeVc0R2FaUUJXNDlyWnFOQitCYjNBK0JiWVpPdklUeVQzVnR5MFE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN1RD
      Q0FwU2dBd0lCQWdJVUZpcXFrYTZ2OW4zRVNlMlo2UzgxYzJ4WUVsRXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpOREEwTVRBd056RXdNREJhRncweU5UQTBNVEF3TnpFMU1EQmFNSGd4
      Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4
      RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1I
      WTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRcXlQbzJiclM0amVzWlJ0TUpGTnM1CnNCR2U3akdO
      OWtrakxsTytjdzBMKy9JWWROdkt0UE41Nkl1UFB1UGdSSUdIcW0vUmxNVGkwVStMYU1KOVhXakwK
      bzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURW
      UjBPQkJZRQpGR2tJM1J2NzNja21BT3ZIUG5IbEZYRUtZYjEyTUI4R0ExVWRJd1FZTUJhQUZDTERY
      TDIzMjQrK25kV2MyZ1dQCnFPZi9jMWxwTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUWTJO
      MlJtWm1NMU56UXROWEZ4YzNRd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZ
      bUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZ
      WFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZ
      MkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVB
      d0lEUndBd1JBSWdaTHNrRTc2bWZiYlhURG1uVURZR3V2M1h4Ri9nSTNCdnh6YTdoNkZoMGZjQwpJ
      RXZqbnIydDBoTytwWTZnM0IwcmJGZ01MQWdPSlNGd3JaY3c0NlEzeHV3cQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVjRFpzMDMwdjZqY0pKQ3hOb1QrS0s4Y2N5amt3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTkRBME1UQXdOekF5TUROYUZ3MHlOekF4TWprd056
      QXlNRE5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSV05H
      QkJQWHJsbTM2YlB1SGNndWFYLzF6QkJ5L3JaWUlYRGtycG9DTTU1UHZhWW4zMkFhemhvT28zQmt0
      Kwp1Y3ZGbithSVJZZzFRUU9yb3EreFRXdVNvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUlzTmN2YmZiajc2ZDFaemFCWStvNS85
      eldXa3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnTEN2WVUxYnlqM3VwZ1RMRXdpNWN3SEV2cEE0
      enB0U0R3Q1k0TGpNYlUyTUNJUUMvdTdWKwp5VzRHYVpRQlc0OXJacU5CK0JiM0ErQmJZWk92SVR5
      VDNWdHkwUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVycxIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggS
      BggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoS
      CBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0
      aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhII
      CgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoG
      QWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6
      NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8w
      EgAaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMS
      GBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFk
      bWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.25
